logger: {
  file: logs/livhub.log,
  level: debug,
  formatter: text, # text or json
  format: '2006-01-02 15:04:05',
  console: true,
  color: true,
  reportcaller: false,
  maxAge: 72,
  rotationTime: 24,
  rotationCount: 5,
  rotationSize: 100,
  filePattern: '%Y%m%d',
}

whip: {
  http: {
    httpAddr: ":7001",
    cert: "",
    key: "",
    allowOrigin: ["*"],
    headers: {
      WebRTC: Whip,
    }
  }
}

pms: {
  keyFrameIntervalSeconds: 0,
  joinTimeoutSeconds: 10,
  http: {
    httpAddr: ":7002",
    cert: "",
    key: "",
    allowOrigin: ["*"],
    headers: {
      WebRTC: pms,
    }
  }
}

webrtc: {
  default: {
    useIceLite: true,
    nat1to1Ips: ["127.0.0.1", "192.168.100.253", "169.254.176.67", "192.168.3.123"],
  # nat1to1Ips: ["127.0.0.1/127.0.0.1", "192.168.100.253/192.168.100.253", "169.254.176.67/169.254.176.67"],
    autoGenerateExternalIp: true,
  #  icePortRange: "7300-7400",
    udpMuxPort: "8888-8888",
  #  tcpPort: 8888,
    iceServers: ["stun.l.google.com:19302"],
    useMdns: true,
    ice_config: {
      "minTcpICEConnectTimeout": 10,
      "iceFailedTimeout": 10,
      "maxTcpICEConnectTimeout": 20,
      "iceDisconnectedTimeout": 5,
    }
  }
}

rtsp: {
  server: {
    addr: "tcp://:3654",
    tcp: {
      Multicore: true,
      NemEventLoop: 10,
      TCPNoDelay: 0,
      LockOSThread: true,
      LogLevel: -1,
      ReusePort: true,
      ReuseAddr: true,
      SocketRecvBuffer: 1024,
    }
  }
}
