logger: {
  file: logs/neon.log,
  level: debug,
  formatter: text, # text or json
  format: '2006-01-02 15:04:05',
  console: true,
  color: true,
  reportcaller: false,
  maxAge: 72,
  rotationTime: 24,
  rotationCount: 5,
  rotationSize: 100,
  filePattern: '%Y%m%d',
}

whip: {
  http: {
    httpAddr: ":7001",
    cert: "",
    key: "",
    allowOrigin: ["*"],
    headers: {
      WebRTC: Whip,
    }
  }
}

pms: {
  http: {
    httpAddr: ":7002",
    cert: "",
    key: "",
    allowOrigin: ["*"],
    headers: {
      WebRTC: pms,
    }
  }
}

webrtc: {
    trackingPackets: 500,
    maxBitRate: 10000000,
    singleport: 5000,
    portrange: [1937, 1938],
    candidates: {
      icelite: true,
      nat1to1: [],
    },
    sdpsemantics: "unified-plan-with-fallback",
    mdns: true,
    timeouts: {
      disconnected: 5,
      failed: 20,
      keepalive: 2,
    },
    iceserver: {
      urls: ["stun:stun.l.google.com:19302"],
      username: "",
      credential: "",
    }
}

rtsp: {
  server: {
    addr: "tcp://:3654",
    tcp: {
      Multicore: true,
      NemEventLoop: 10,
      TCPNoDelay: 0,
      LockOSThread: true,
      LogLevel: -1,
      ReusePort: true,
      ReuseAddr: true,
      SocketRecvBuffer: 1024,
    }
  }
}
